### ISSUE TITLE
Tested a few API both failed, invalid JSON source / [object Object]

### ISSUE THREAD

**Issue by Jeradin** [Mashape/apiembed#10]
Hello, looks like a really cool service! 

Things I noticed are both of the below are compress and also json-escape for URLs.

I had trouble with the below API which is from the json REST API being built into WordPress.
https://loqu.st/wp-json/ 
```invalid JSON source, please review the documentation and try again```

Also this API from contentDM
https://server16622.contentdm.oclc.org/dmwebservices/index.php?q=dmGetCollectionList/json

The message I get is :
```[object Object],[object Object], please review the documentation and try again```

**Comment by ahmadnassri** [comment]
hey @Jeradin the only format we support at the moment is the [HAR Request format](http://www.softwareishard.com/blog/har-12-spec/#request)

out of curiosity, what format are those APIs documented in?

**Comment by Jeradin** [comment]
Thank you @ahmadnassri for the reply.

I am not able to find what format the  first API is set to, I do know it is positioned to be part of the WordPress.org core in version 4.5.

http://wp-api.org/
https://github.com/WP-API/WP-API

The second API: http://www.contentdm.org/help6/custom/customize2a.asp

Either way thanks again for your time!

**Comment by ahmadnassri** [comment]
thanks @Jeradin we might end up supporting additional formats in the future, for now its just HAR :)
