### ISSUE TITLE
Could not load JSON source, please review the documentation and try again

### ISSUE THREAD

**Issue by NadaBen** [Mashape/apiembed#22]
Hello, please i need your help, I'm using 
`<iframe src="//api.apiembed.com/?source=http://localhost/test/demo.json&targets=all" frameborder="0" scrolling="no" width="100%" height="300px" seamless></iframe> `

but it gives me this error 
`Could not load JSON source, please review the documentation and try again`

my jsonfile is saved locally, I am stilling in localhost, and it's as follows:
`{
  "method": "POST",
  "url": "http://localhost/test/web/app_dev.php/v1/photos",
  "httpVersion": "HTTP/1.1",
  "queryString": [
    { "image": "photos/1.jpg", "value": "photos/1.jpg" }
    ],
  "headers": [
    { "name": "Accept", "value": "application/json" },
    { "name": "Content-Type", "value": "application/json" }
  ],

  "postData": {
    "mimeType": "application/json",
    "image": "{\"photos/1.jpg\": \"photos/1.jpg\"}"
  }
}
`

**Comment by ahmadnassri** [comment]
you can't use localhost urls with this online service.
