### ISSUE TITLE
Showing target choices when there is only one target

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/apiembed#3]
If there is only one implementation for a target then we shouldn't ask.

![screen shot 2015-03-11 at 4 27 08 pm](https://cloud.githubusercontent.com/assets/24260/6609194/d5c04cc2-c80b-11e4-921e-627b8c6235fc.png)

**Comment by ahmadnassri** [comment]
:+1:  was holding back since more are coming ... though for ocaml doubt there will be (didn't even anticipate we'll have that one on launch)

**Comment by montanaflynn** [comment]
Couldn't we add the logic of "If there's more than one, show up" instead of doing it on a per target basis?

**Comment by ahmadnassri** [comment]
yeah, that's what i'll be doing ...

**Comment by SGrondin** [comment]
There won't be another one for OCaml, you can just remove the All checkbox, but I think it's important to keep the "Cohttp" somewhere because it's important information.

**Comment by ahmadnassri** [comment]
I think a design update is needed, I wanna be able to show the "library" info somewhere, link to source ... @jitachi

**Comment by montanaflynn** [comment]
Should still remove it for now because it's really weird. That OCaml uses a library needs to be apparent inside the code or embedded widget since people will be seeing it embedded in another website. A code comment at the top would be sufficient, just like we do with Unirest on mashape.

**Comment by ahmadnassri** [comment]
@montanaflynn yeah, I think we're saying the same thing, I mean for inside the widget, not the site, be nice to give credit to the library source & even the contributing author for each target converter 

something along the lines of:

*[Unirest](http://unirest.io) support by [@therebelrobot](https://github.com/therebelrobot)*

**Comment by ahmadnassri** [comment]
something along those lines:

![image](https://cloud.githubusercontent.com/assets/183195/6612907/037da4da-c85b-11e4-98ca-42f284108199.png)

**Comment by ahmadnassri** [comment]
maybe for libraries the text would be: `COhttp support by ...` since the language name is already obvious in the tab

**Comment by montanaflynn** [comment]
I was mostly replying to @SGrondin to make sure the library is mentioned inside the embedded widget.

So in the top of his code he would put something like:
// Requires https://github.com/mirage/ocaml-cohttp

and we would do the same for Unirest and other non-native targets.

**Comment by ahmadnassri** [comment]
ah, code comments, yes those are good.

**Comment by SGrondin** [comment]
I'll add a comment.
