### ISSUE TITLE
Selecting targets UI

### ISSUE THREAD

**Issue by montanaflynn** [Mashape/apiembed#4]
Instead of having an all checkbox it might be wise to have a "select all" / "unselect all" action and by default have them all selected. 

The problem with it currently is that none are selected when loading the page even though they all show up in the preview and if you select all it disables the other checkboxes, causing a lot of clicks to get rid of httpie and wget.

Current: 
![screen shot 2015-03-11 at 4 31 24 pm](https://cloud.githubusercontent.com/assets/24260/6609275/ac271a0c-c80c-11e4-9a87-328c72a5686a.png)

Proposed:
![screen shot 2015-03-11 at 4 37 33 pm](https://cloud.githubusercontent.com/assets/24260/6609304/fb765492-c80c-11e4-86a2-5af9c41f7e53.png)

**Comment by ahmadnassri** [comment]
I like this idea ... @jitachi what do you think?

**Comment by jitachigarcia** [comment]
yeah, just put them in the right side.
