### ISSUE TITLE
[golang example] Use http.DefaultClient instead of your own client

### ISSUE THREAD

**Issue by DanielHeath** [Mashape/apiembed#5]
```go
package main

import (
	"fmt"
	"strings"
	"net/http"
	"io/ioutil"
)

func main() {

	url := "http://mockbin.com/request?foo=bar&foo=baz"

	payload := strings.NewReader("{\"foo\": \"bar\"}")

	req, _ := http.NewRequest("POST", url, payload)

	req.Header.Add("cookie", "foo=bar; bar=baz")
	req.Header.Add("accept", "application/json")
	req.Header.Add("content-type", "application/json")

	res, _ := http.DefaultClient.Do(req)

	defer res.Body.Close()
	body, _ := ioutil.ReadAll(res.Body)

	fmt.Println(res)
	fmt.Println(string(body))

}
```

**Comment by montanaflynn** [comment]
Is there a benefit to this approach besides one less line? The [httpsnippet](https://github.com/Mashape/httpsnippet) project is using the client for a timeout option and I'll probably add a redirect option as well.

**Comment by DanielHeath** [comment]
Nothing wrong with it, it's just not idiomatic go (unless you use the client to do something).

**Comment by montanaflynn** [comment]
Thanks for the input. Like I said the underlying library has a timeout option so that's why it's there, I might make it as you suggest for when the option is not invoked or maybe just set a default timeout.

**Comment by ahmadnassri** [comment]
@montana you could also make two separate implementations and let the user decide which they'd like to use.

also, this would be better suited as a discussion on https://github.com/Mashape/httpsnippet

**Comment by montanaflynn** [comment]
Closed with https://github.com/Mashape/httpsnippet/commit/45a0e36098fc8cdf05f7938a8917bb6221ba8298
