### ISSUE TITLE
Great work!  License?

### ISSUE THREAD

**Issue by ianakelly** [Mashape/apiembed#9]
Very nice work guys really like it!  Says Open Source but the repo has no license that I saw - Without a license its fully under Copywrite.  Things like Kong have a license file - https://github.com/Mashape/kong/blob/master/LICENSE

Oversight maybe?

**Comment by ahmadnassri** [comment]
@ianakelly oops! can't believe I missed that! we take it for granted sometimes as almost everything we do is open-sourced under MIT :)

now fixed, thanks for pointing out :)
